### ISSUE TITLE
wpan-tools 0.7 fails to build with libnl 3.3

### ISSUE THREAD

**Issue by jengelh** [linux-wpan/wpan-tools#14]
```
[    7s] gcc -DHAVE_CONFIG_H -I. -I..     -I/usr/include/libnl3 -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -c -o iwpan-interface.o `test -f 'interface.c' || echo './'`interface.c
[    7s] In file included from info.c:12:0:
[    7s] nl_extras.h:9:0: warning: "NLA_PUT_S8" redefined
[    7s]  #define NLA_PUT_S8(n, attrtype, value) \
[    7s]  
[    7s] In file included from /usr/include/libnl3/netlink/msg.h:17:0,
[    7s]                  from /usr/include/libnl3/netlink/genl/genl.h:16,
[    7s]                  from info.c:5:
[    7s] /usr/include/libnl3/netlink/attr.h:190:0: note: this is the location of the previous definition
[    7s]  #define NLA_PUT_S8(msg, attrtype, value) \
[    7s]  
[    7s] In file included from info.c:12:0:
[    7s] nl_extras.h:12:22: error: conflicting types for 'nla_get_s8'
[    7s]  static inline int8_t nla_get_s8(struct nlattr *nla)
```

**Comment by jengelh** [comment]
Apparently fixed in master… needless to say when we distros go looking, it's tarballs first.

**Comment by tracernz** [comment]
Would be very much appreciated if a new release could be put out so that packagers don't have to build from git. 😄
